name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["11.4.2", "11.4.1", "11.4", "11.3.2", "11.3.1", "11.3"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Setup Ghidra
        uses: antoniovazquezblanco/setup-ghidra@cacffdd46c5f53356e6a7822a2743a39f57d1958
        with:
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ matrix.ghidra }}
      - name: Test
        run: gradle -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }} test
