name: Publish unstable builds

on:
  push:
    branches:
      - main

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghidra: ["11.2", "11.1.2"]
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: Setup Ghidra
        uses: er28-0652/setup-ghidra@b53614dada0a16e3c342277caae905b96d803109
        with:
          version: ${{ matrix.ghidra }}
      - name: Download stdump
        run: bash ./os/download.sh
      - name: Build Extension
        run: gradle -PGHIDRA_INSTALL_DIR=${{ env.GHIDRA_INSTALL_DIR }} buildExtension
      - name: Release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/*ghidra-emotionengine-reloaded.zip
          tag: "unstable"
          overwrite: true
          file_glob: true
